name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: {java-version: '17', distribution: 'temurin'}
      - uses: android-actions/setup-android@v3
      - name: Accept SDK Licenses
        run: |
          mkdir -p "$ANDROID_HOME/licenses"
          echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8a7d" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
      - name: Build with Gradle
        # --no-daemon aur --build-cache false se memory error nahi aayega
        run: ./gradlew clean assembleDebug --no-daemon --no-build-cache --stacktrace
